// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/music-requests': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/music-requests.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/music-requests.post').default>>>>
    }
    '/api/admin/optimize': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/optimize.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/update-elo': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/update-elo.post').default>>>>
    }
    '/api/auth/update-stats': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/update-stats.post').default>>>>
    }
    '/api/maps/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id].patch').default>>>>
    }
    '/api/maps/:id/audio-chunk': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id]/audio-chunk.post').default>>>>
    }
    '/api/maps/:id/audio': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id]/audio.get').default>>>>
    }
    '/api/maps/:id/rate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id]/rate.post').default>>>>
    }
    '/api/maps/:id/record': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id]/record.post').default>>>>
    }
    '/api/maps': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/index.post').default>>>>
    }
    '/api/rooms/:id/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/chat.post').default>>>>
    }
    '/api/rooms/:id/leave': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/leave.post').default>>>>
    }
    '/api/rooms/:id/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/start.post').default>>>>
    }
    '/api/rooms/:id/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/status.get').default>>>>
    }
    '/api/rooms/:id/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/[id]/update.post').default>>>>
    }
    '/api/rooms/cleanup': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/cleanup.get').default>>>>
    }
    '/api/rooms/clear': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/clear.post').default>>>>
    }
    '/api/rooms/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/create.post').default>>>>
    }
    '/api/rooms': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/index.get').default>>>>
    }
    '/api/rooms/join': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/join.post').default>>>>
    }
    '/api/rooms/next-map': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rooms/next-map.post').default>>>>
    }
    '/api/samples': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/samples.get').default>>>>
    }
    '/api/youtube': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/youtube.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}