// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/update-stats': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/update-stats.post').default>>>>
    }
    '/api/maps/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id].patch').default>>>>
    }
    '/api/maps/:id/record': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/[id]/record.post').default>>>>
    }
    '/api/maps': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/maps/index.post').default>>>>
    }
    '/api/matchmaking/find': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matchmaking/find.post').default>>>>
    }
    '/api/matchmaking/status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matchmaking/status.post').default>>>>
    }
    '/api/youtube': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/youtube.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}